//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AGM.rc
//
#define IDDELETE                        3
#define ID_MAP_SAVEAS                   3
#define ID_MAP_LOAD                     5
#define ID_MAP_NEW                      6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_PROPERTIES                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_MAP                         104
#define IDS_DELETE                      104
#define IDD_SECTDLG                     105
#define IDS_ADDBASE                     105
#define ID_SECTWND                      106
#define IDS_ADDROCK                     106
#define IDD_ALEPHDLG                    107
#define IDS_COPY                        107
#define IDC_2DMAP                       108
#define IDD_BASEDLG                     109
#define IDM_ADDBASE                     110
#define IDM_ADDROCK                     111
#define IDM_PROPS                       112
#define IDM_DEL                         113
#define IDM_DELBASES                    114
#define IDM_DELROCKS                    115
#define IDM_JUMP                        116
#define IDM_COPYOBJECT                  117
#define IDM_PASTEOBJECT                 118
#define IDM_SECTPROPS                   119
#define IDM_ADDROCK_ASTERIOD            120
#define IDM_ADDROCK_HELIUM              121
#define IDM_ADDROCK_URANIUM             122
#define IDM_ADDROCK_SILICON             123
#define IDM_ADDROCK_CARBON              124
#define IDM_RANDOMIZE_ROCKS             125
#define IDM_RANDOMIZE_ALEPHS            126
#define IDM_ADDROCK_ASTERIODS           127
#define IDR_MAINFRAME                   128
#define IDM_ADDROCK_THORIUM             128
#define IDD_ROCKDLG                     129
#define IDM_ADDROCKSLAYOUT              129
#define IDM_TPL_ALEPHS                  134
#define IDR_MAINFRAME1                  135
#define IDM_TPL_ROCKS                   135
#define IDM_TPL_SECTORS                 136
#define IDD_ROCKTPLDLG                  137
#define IDR_ACCELERATOR_SECTWND         137
#define IDD_GETNUMDLG                   139
#define IDD_ROCKSLAYOUTDLG              140
#define IDRELOAD                        141
#define IDD_RANDOMDLG                   142
#define IDC_EDITRES                     1002
#define IDC_LockGameOpen                1003
#define IDC_LockTeamSettings            1004
#define IDC_InitialMinersPerTeam        1005
#define IDC_MaxMinersPerTeam            1006
#define IDC_AllowSupremacyPath          1007
#define IDC_AllowExpansionPath          1008
#define IDC_AllowTacticalPath           1009
#define IDC_AllowShipyardPath           1010
#define IDC_ShowMap                     1011
#define IDC_Teams                       1012
#define IDC_CivIDs1                     1013
#define IDC_CivIDs2                     1014
#define IDC_CivIDs3                     1015
#define IDC_CivIDs4                     1016
#define IDC_CivIDs5                     1017
#define IDC_CivIDs6                     1018
#define IDC_TeamName1                   1019
#define IDC_TeamName2                   1020
#define IDC_TeamName3                   1021
#define IDC_TeamName4                   1022
#define IDC_TeamName5                   1023
#define IDC_TeamName6                   1024
#define IDC_STATIC_TEAM1                1025
#define IDC_STATIC_TEAM2                1026
#define IDC_STATIC_TEAM3                1027
#define IDC_STATIC_TEAM4                1028
#define IDC_STATIC_TEAM5                1029
#define IDC_STATIC_TEAM6                1030
#define IDC_Drones                      1031
#define IDC_MaxImbalance                1032
#define IDC_StartingMoney               1033
#define IDC_TotalMaxPlayers             1034
#define IDC_He3Density                  1035
#define IDC_PlayerSectorMineableAsteroids 1036
#define IDC_NeutralSectorMineableAsteroids 1037
#define IDC_PlayerSectorSpecialAsteroids 1038
#define IDC_NeutralSectorSpecialAsteroids 1039
#define IDC_PlayerSectorAsteroids       1040
#define IDC_NeutralSectorAsteroids      1041
#define IDC_MinPlayers                  1042
#define IDC_GameName                    1043
#define IDC_StoryText                   1044
#define IDC_BUT_LOADREG                 1045
#define IDC_BUT_SAVEREG                 1046
#define IDC_BUT_About                   1047
#define IDC_MaxPlayers                  1048
#define IDC_CustomMap                   1049
#define IDC_BUT_MAP                     1050
#define IDC_BUT_LOADFILE                1051
#define IDC_BUT_SAVEFILE                1052
#define IDC_BUT_SAVEFILE2               1053
#define IDC_AllowEmptyTeams             1054
#define IDC_BUT_RESET                   1055
#define IDC_MapType                     1056
#define IDC_LB_SECTORS                  1057
#define IDC_IsConquest                  1057
#define IDC_MAPEDIT                     1058
#define IDC_IsDM                        1059
#define IDC_DMKills                     1060
#define IDC_EjectPods                   1061
#define IDC_STATIC_Sectors              1062
#define IDC_FriendlyFire                1062
#define IDC_Lives                       1063
#define IDC_StaticCore                  1064
#define IDC_BUT_CORE                    1065
#define IDC_IsMoney                     1066
#define IDC_StatsCount                  1067
#define IDC_GoalMoney                   1068
#define IDC_StatsCount2                 1069
#define IDC_SquadGame                   1069
#define IDC_S_MAP                       1070
#define IDC_MapSize                     1071
#define IDC_S_CUSTMAP                   1072
#define IDC_SECT_GLOBE                  1073
#define IDC_SECT_NEBBG                  1074
#define IDC_SECT_TEAM                   1075
#define IDC_S_Globe                     1078
#define IDC_S_Nebbg                     1079
#define IDC_S_Globe2                    1079
#define IDC_S_Team                      1080
#define IDC_SECT_NAME                   1081
#define IDC_SECT_POSX                   1082
#define IDC_S_Name                      1083
#define IDC_SECT_COL1                   1084
#define IDC_SECT_LITEX                  1084
#define IDC_SECT_LITEZ                  1085
#define IDC_SECT_COL2                   1086
#define IDC_SECT_DEBRISC                1086
#define IDC_SECT_COL3                   1087
#define IDC_SECT_STARSEED               1087
#define IDC_SECT_COL4                   1088
#define IDC_SECT_PLLAT                  1088
#define IDC_SECT_COL5                   1089
#define IDC_SECT_LightColor             1089
#define IDC_S_Col1                      1090
#define IDC_SECT_PLRADIUS               1090
#define IDC_SECT_POSY                   1091
#define IDC_S_Col2                      1092
#define IDC_SECT_LITEY                  1092
#define IDC_S_Col3                      1093
#define IDC_SECT_STARSC                 1093
#define IDC_S_Col4                      1094
#define IDC_SECT_PLLONG                 1094
#define IDC_S_Col5                      1095
#define IDC_S_PosX                      1096
#define IDC_S_PosY                      1097
#define IDC_S_PosX2                     1098
#define IDC_2DMAP_OLD                   1099
#define IDC_S_PosY2                     1099
#define IDC_S_PosX3                     1100
#define ID_MAP_S_APPLY                  1101
#define ID_MAP_S_DELETE                 1102
#define ID_SDLG_CANCEL                  1103
#define IDC_S_PosY3                     1104
#define IDC_S_PosY4                     1105
#define IDC_SECTVIEW_FRAME              1106
#define IDC_S_PosX4                     1106
#define IDC_S_PosX5                     1107
#define IDC_S_PosY5                     1108
#define IDC_S_PosX6                     1109
#define IDC_A_NAME                      1113
#define IDC_AL_Name                     1114
#define IDC_ALEPH_POSX                  1115
#define IDC_ALEPH_POSY                  1116
#define IDC_ALEPH_POSZ                  1117
#define IDC_ALEPH_RENDER                1118
#define IDC_ALEPH_SIG                   1119
#define IDC_ALEPH_RADIUS                1120
#define IDC_AL_x                        1121
#define IDC_AL_y                        1122
#define IDC_AL_z                        1123
#define IDC_AL_Name2                    1124
#define IDC_AL_z4                       1124
#define IDC_AL_Name3                    1125
#define IDC_AL_Name4                    1126
#define IDC_AL_x3                       1126
#define IDC_AL_y3                       1127
#define IDC_ALEPH_O1X                   1127
#define IDC_AL_z5                       1128
#define IDC_ALEPH_O1Y                   1128
#define IDC_ALEPH_O1Z                   1129
#define IDC_ROCK_HE2capt                1129
#define IDC_AL_x2                       1130
#define IDC_AL_y2                       1131
#define IDC_AL_z2                       1132
#define IDC_AL_x4                       1132
#define IDC_ALEPH_SPINX                 1133
#define IDC_AL_Name6                    1133
#define IDC_ALEPH_SPINY                 1134
#define IDC_AL_Name7                    1134
#define IDC_ALEPH_SPINZ                 1135
#define IDC_AL_Name8                    1135
#define IDC_S_Base                      1136
#define IDC_ALEPH_SPIN_SPEED            1136
#define IDC_A_RADIUS_MIN                1136
#define IDC_BASE_TEAM                   1137
#define IDC_AL_z3                       1137
#define IDC_A_RADIUS_MAX                1137
#define IDC_AL_y4                       1138
#define IDC_BASE_TYPENAME               1138
#define IDC_BASE_SPINX                  1139
#define IDC_AL_x6                       1139
#define IDC_BASE_SPINY                  1140
#define IDC_A_ICON                      1140
#define IDC_BASE_SPINZ                  1141
#define IDC_AL_Name5                    1141
#define IDC_BASE_SPIN_SPEED             1142
#define IDC_BASE_NAME                   1143
#define IDC_BASE_O1X                    1144
#define IDC_BASE_O1Y                    1145
#define IDC_BASE_O1Z                    1146
#define IDC_BASE_O2X                    1147
#define IDC_BASE_O2Y                    1148
#define IDC_BASE_O2Z                    1149
#define IDC_BASE_POSX                   1150
#define IDC_BASE_POSY                   1151
#define IDC_BASE_POSZ                   1152
#define ID_MAP_SAVE                     1153
#define IDC_ROCK_ICON                   1153
#define IDC_BASE_FACTION                1153
#define ID_MAP_QUIT                     1154
#define IDC_S_Base2                     1154
#define IDC_MAP_NAME                    1155
#define IDC_ALEPH_AUTOORIENT            1156
#define IDC_ALEPH_NOSPIN                1157
#define IDC_ROCK_NHIDDEN                1158
#define IDC_ALEPH_FIXED                 1158
#define IDC_ROCK_F8                     1159
#define IDC_ROCK_F1                     1160
#define IDC_ROCK_F16                    1161
#define IDC_ROCK_F32                    1162
#define IDC_ROCK_F64                    1163
#define IDC_ROCK_HE1                    1164
#define IDC_ROCK_HE2                    1165
#define IDC_ROCK_SIG                    1166
#define IDC_ROCK_RADIUS                 1167
#define IDC_ROCK_HP                     1168
#define IDC_RADIUS_MIN                  1169
#define IDC_ROCK_F4                     1169
#define IDC_ROCK_PHANTOM                1170
#define IDC_RADIUS_MIN2                 1170
#define IDC_RADIUS_MAX                  1170
#define IDC_ROCK_GAUGE                  1171
#define IDC_ROCK_TEMPLATE               1172
#define IDC_ROCK_RENDER                 1173
#define IDC_ROCK_NAME                   1174
#define IDC_ROCK_POSX                   1175
#define IDC_ROCK_POSY                   1176
#define IDC_ROCK_POSZ                   1177
#define IDC_ROCK_SPINX                  1178
#define IDC_ROCK_SPINY                  1179
#define IDC_ROCK_SPINZ                  1180
#define IDC_ROCK_SPIN_SPEED             1181
#define IDC_ROCK_O2Z                    1182
#define IDC_ROCK_O2Y                    1183
#define IDC_ROCK_O2X                    1184
#define IDC_ROCK_O1Z                    1185
#define IDC_ROCK_O1Y                    1186
#define IDC_ROCK_O1X                    1187
#define IDC_ROCK_HE1capt                1188
#define IDC_ROCK_RENDER_CUSTOM          1189
#define IDC_B_TEMPLATES                 1189
#define IDC_BASE_SETTYPE                1190
#define IDC_BASE_TYPE                   1191
#define IDC_MAP_SNAP                    1194
#define IDC_MAP_GRID                    1195
#define IDAPPLYTOSECT                   1195
#define IDC_B_DELALL_ALEPHS             1196
#define IDAPPLYTOALL                    1196
#define IDC_B_DELALL_BASES              1197
#define IDC_APPLYSPIN                   1197
#define IDC_B_DELALL_ROCKS              1198
#define IDC_S_INCAPPLY                  1198
#define IDC_RADIUS_RND                  1199
#define IDC_B_RDALL_ALEPHS              1200
#define IDC_SIG_AUTO                    1200
#define IDC_B_RDALL_ROCKS               1201
#define IDC_HP_AUTO                     1201
#define IDC_RADIUS_INC                  1202
#define IDC_SIG_INC                     1203
#define IDC_HP_INC                      1204
#define IDC_TAB_ROCKS                   1205
#define IDC_S_RADFRAME                  1206
#define IDC_NUMBER                      1207
#define IDC_CAPTION                     1208
#define IDC_C1X                         1210
#define IDC_C1Y                         1211
#define IDC_C1Z                         1212
#define IDC_EDIT1                       1212
#define IDC_GameLength                  1212
#define IDC_SVRLOG                      1212
#define IDC_CORE_NAME                   1212
#define IDC_ROCK_CUSTOM_MODEL           1212
#define IDC_SECT_GLOBENAME              1212
#define IDC_RA1                         1213
#define IDC_RA2                         1214
#define IDC_RA3                         1215
#define IDC_RADIUS1                     1216
#define IDC_RA4                         1216
#define IDC_RA5                         1217
#define IDC_VARZ                        1219
#define IDC_CKZVIEW                     1219
#define IDC_DEFS                        1220
#define IDC_CKB19                       1221
#define IDC_CKB42                       1222
#define IDC_B_RENAME_SECTORS            1222
#define IDC_PLANET                      1223
#define IDC_NBROCKS                     1224
#define IDC_SVRCHAT                     1224
#define IDC_SVRBTCHANGE                 1225
#define IDC_SVRBTPARAMS                 1226
#define IDC_SVRBTCHAT                   1227
#define IDC_CORELOAD                    1228
#define IDC_BUTTON2                     1229
#define IDC_ABOUT                       1229
#define IDC_BUTTON1                     1233
#define IDC_A_ICONBMP                   1233
#define DYNMENUSID                      5000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1234
#define _APS_NEXT_SYMED_VALUE           145
#endif
#endif
